# preperations

In [1]:
import numpy as np
import pandas as pd

In [2]:
train_original = pd.read_csv("data/train.csv")
test_original = pd.read_csv("data/test.csv")

In [3]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
train_original.head()

,kaltmiete_listing,overpriced,floor,furnished,num_photos,total_floors,building_age_years,listing_date,wg_typ,year_built,priority_score,num_rooms,plz,balcony,days_online,living_area_m2,stadtteil,living_area_text,energieausweis,dist_uni_km,contact_type,heating_type,kitchen,dist_uni_min,elevator,clicks_last_week,listing_id,nebenkosten_eur
0,325 €,False,2. OG,teilmöbliert,16,2,126,08.05.2026,gemischt,1900,7,3.0,93051,nein,52,21.2,Königswiesen,21.2 m2,A+,7.5,Genossenschaft,Nachtspeicher,Pantry,30,ja,211,INS-2026-49534,57
1,335 €,True,3. OG,möbliert,10,2,105,04.04.2026,gemischt,1921,9,2.0,93055,ja,71,18.8,Burgweinting,18.8 m2,A+,10.8,Makler,Gasetagenheizung,Einbauküche,44,nein,52,INS-2026-39524,126
2,491 warm,False,EG,unmöbliert,10,2,50,18.03.2026,Studenten-WG,1976,5,1.0,93053,ja,40,16.3,Galgenberg,16.3 m2,E,10.7,Privat,Gasetagenheizung,Einbauküche,43,nein,65,INS-2026-45414,157
3,373 €,False,2. OG,unmöbliert,10,2,18,19.04.2026,Studenten-WG,2008,6,3.0,93059,nein,23,20.4,Stadtamhof,"20,4 qm",E,10.9,Privat,Fernwärme,Einbauküche,44,nein,227,INS-2026-36290,164
4,328,False,EG,teilmöbliert,10,4,35,16.02.2026,Studenten-WG,1991,7,3.0,93049,nein,71,22.5,Karthaus-Prüll,22 m²,D,9.4,Privat,Zentralheizung,Einbauküche,37,nein,94,INS-2026-68392,149

In [5]:
print(train_original.columns)
print(test_original.columns)
print(train_original.dtypes)
print(test_original.dtypes)

Index(['kaltmiete_listing', 'overpriced', 'floor', 'furnished', 'num_photos',
       'total_floors', 'building_age_years', 'listing_date', 'wg_typ',
       'year_built', 'priority_score', 'num_rooms', 'plz', 'balcony',
       'days_online', 'living_area_m2', 'stadtteil', 'living_area_text',
       'energieausweis', 'dist_uni_km', 'contact_type', 'heating_type',
       'kitchen', 'dist_uni_min', 'elevator', 'clicks_last_week', 'listing_id',
       'nebenkosten_eur'],
      dtype='object')
Index(['floor', 'furnished', 'num_photos', 'total_floors',
       'building_age_years', 'listing_date', 'wg_typ', 'year_built',
       'priority_score', 'num_rooms', 'plz', 'balcony', 'days_online',
       'living_area_m2', 'stadtteil', 'living_area_text', 'energieausweis',
       'dist_uni_km', 'contact_type', 'heating_type', 'kitchen',
       'dist_uni_min', 'elevator', 'clicks_last_week', 'listing_id',
       'nebenkosten_eur'],
      dtype='object')
kaltmiete_listing      object
overpriced               bool
floor                  object
furnished              object
num_photos              int64
total_floors            int64
building_age_years      int64
listing_date           object
wg_typ                 object
year_built              int64
priority_score          int64
num_rooms             float64
plz                     int64
balcony                object
days_online             int64
living_area_m2        float64
stadtteil              object
living_area_text       object
energieausweis         object
dist_uni_km           float64
contact_type           object
heating_type           object
kitchen                object
dist_uni_min            int64
elevator               object
clicks_last_week        int64
listing_id             object
nebenkosten_eur         int64
dtype: object
floor                  object
furnished              object
num_photos              int64
total_floors            int64
building_age_years      int64
listing_date           object
wg_typ                 object
year_built              int64
priority_score          int64
num_rooms             float64
plz                     int64
balcony                object
days_online             int64
living_area_m2        float64
stadtteil              object
living_area_text       object
energieausweis         object
dist_uni_km           float64
contact_type           object
heating_type           object
kitchen                object
dist_uni_min            int64
elevator               object
clicks_last_week        int64
listing_id             object
nebenkosten_eur         int64
dtype: object

# data cleaning and preprocessing

### orga

- DONE kaltmiete_listing - muss preprocessed werden
- DONE overpriced ist sauber
- DONE floor kann gemapped werden (von -1 bis 4) - weitere spalte is_dachgeschoss[True,False] kann hinzugefügt werden zum trainieren
- DONE furnished keine Ahnung ob man das ordinal machen sollte (habs mal ordinal gemacht)
- DONE num_photos droppen
- DONE total_floors wird behalten
- DONE building_age_years wird behalten, ist besser als year_built
- DONE listing_date droppen
- DONE wg_typ wird behalten, denke nicht dass man das ordinal machen sollte. Habs nicht direkt ordinal, aber mit scikit preprocessor transformiert
- DONE year_built droppen
- POTENTIAL_DROP priority_score - !!! Keine Ahnung was das ist!!! kann vermutlich gedroppt werden, wird final mit und ohne getestet
- DONE num_rooms wird behalten
- POTENTIAL_DROP plz wird in String umgewandelt da es keine sinnvolle Ordnung als Zahl dafür gibt
- DONE balcony wird in True/False umgewandelt
- DONE days_online droppen
- DONE living_area_m2 wird behalten, das ist sauber (wird mit benutzt um outlyer in den preis/qm zu droppen)
- POTENTIAL_DROP stadtteil wird behalten - evtl mit plz blabla doppelter einfluß
- DONE living_area_text droppen, sind großteils bei living_area_m2, aber weichen manchmal ab
- DONE energieausweis wird ordinal gemacht
- POTENTIAL_DROP dist_uni_km wird behalten
- DONE contact_type wird behalten
- DONE heating_Type wird behalten
- DONE kitchen wird behalten, ordinal machen könnte sinn machen aber nicht implementiert. Ich hätte es nicht ordinal gemacht.
- POTENTIAL_DROP dist_uni_min wird behalten, ist ein bissl was anderes als dist_uni_km inmyopinion - aber vllt könnte man eins von beiden droppen
- DONE elevator wird in True/False umgewandelt
- DONE clicks_last_week wird behalten - könnte vorraussagen ob die miete für die qm preise attraktiv ist
- DONE listing_id droppen
- DONE nebenkosten_eur wird behalten

In [6]:


for col in train_original.columns:
    print(col)
    print(train_original[col].unique())
    print("-" * 40)

kaltmiete_listing
['325 €' '335 €' '491 warm' ... '290' '530' 'Kaltmiete: 305 €']
----------------------------------------
overpriced
[False  True]
----------------------------------------
floor
['2. OG' '3. OG' 'EG' 'Souterrain' 'DG' '4. OG' '1. OG']
----------------------------------------
furnished
['teilmöbliert' 'möbliert' 'unmöbliert']
----------------------------------------
num_photos
[16 10 21 14 15  6  8  7 19 18  5 12  2  4 23  9 11 25  3 13 24 17 20 22]
----------------------------------------
total_floors
[2 4 1 3 7 6 5]
----------------------------------------
building_age_years
[126 105  50  18  35  15  84   4  30 101 123  92  52 104  76  57  85  47
  78 112  26   9 109  63 122  12  71   2  68  77  91  25   8  17  21 102
 119  51  61  72  33  48  22 113  98  41  42  29  64  60 115  74  45  90
 106  23  28  14  73  24  43  81  87  44  16 116  31  58 100  67  20 121
  46  70  97  10  86  65  93 107 124  38  40  34 110  59  75  66   7  32
 114  99 125  83  80  95  19  96  69  62  13  37  94  88 108  54  39 103
   6  79   5 118   3  53  11  56  82  89 120  27  49 117 111  36  55]
----------------------------------------
listing_date
['08.05.2026' '04.04.2026' '18.03.2026' '19.04.2026' '16.02.2026'
 '22.05.2026' '04.01.2026' '13.02.2026' '17.02.2026' '22.04.2026'
 '14.02.2026' '18.04.2026' '19.03.2026' '21.01.2026' '12.05.2026'
 '02.05.2026' '18.01.2026' '15.03.2026' '20.02.2026' '22.01.2026'
 '22.06.2026' '08.01.2026' '11.06.2026' '17.01.2026' '29.04.2026'
 '12.03.2026' '14.01.2026' '29.06.2026' '15.04.2026' '03.05.2026'
 '31.03.2026' '09.04.2026' '16.03.2026' '04.05.2026' '31.01.2026'
 '09.06.2026' '11.03.2026' '25.05.2026' '28.04.2026' '17.04.2026'
 '25.01.2026' '06.05.2026' '22.03.2026' '04.02.2026' '15.02.2026'
 '21.05.2026' '13.03.2026' '05.01.2026' '02.02.2026' '06.02.2026'
 '12.04.2026' '10.01.2026' '10.06.2026' '28.01.2026' '07.02.2026'
 '08.02.2026' '05.04.2026' '16.06.2026' '24.06.2026' '09.02.2026'
 '16.04.2026' '28.03.2026' '01.06.2026' '10.03.2026' '15.01.2026'
 '12.01.2026' '01.02.2026' '24.02.2026' '24.05.2026' '07.06.2026'
 '21.04.2026' '29.03.2026' '23.05.2026' '04.06.2026' '14.03.2026'
 '02.01.2026' '16.05.2026' '11.02.2026' '12.02.2026' '31.05.2026'
 '19.01.2026' '19.02.2026' '23.03.2026' '25.06.2026' '13.05.2026'
 '10.02.2026' '23.04.2026' '26.03.2026' '10.05.2026' '07.01.2026'
 '07.05.2026' '21.03.2026' '12.06.2026' '22.02.2026' '24.01.2026'
 '30.01.2026' '28.05.2026' '14.06.2026' '09.03.2026' '20.01.2026'
 '27.01.2026' '19.05.2026' '17.06.2026' '06.01.2026' '07.04.2026'
 '27.03.2026' '06.03.2026' '10.04.2026' '25.03.2026' '02.04.2026'
 '17.05.2026' '02.03.2026' '29.05.2026' '28.06.2026' '21.02.2026'
 '08.06.2026' '11.04.2026' '14.05.2026' '17.03.2026' '03.06.2026'
 '05.02.2026' '23.06.2026' '01.05.2026' '03.01.2026' '27.05.2026'
 '07.03.2026' '26.01.2026' '01.03.2026' '02.06.2026' '01.04.2026'
 '28.02.2026' '03.03.2026' '04.03.2026' '03.02.2026' '23.02.2026'
 '27.02.2026' '18.02.2026' '20.05.2026' '26.06.2026' '27.04.2026'
 '26.02.2026' '05.06.2026' '20.06.2026' '26.05.2026' '20.04.2026'
 '24.04.2026' '16.01.2026' '03.04.2026' '25.02.2026' '05.03.2026'
 '20.03.2026' '06.04.2026' '06.06.2026' '13.01.2026' '21.06.2026'
 '29.01.2026' '15.05.2026' '23.01.2026' '09.05.2026' '08.04.2026'
 '30.04.2026' '14.04.2026' '13.06.2026' '05.05.2026' '25.04.2026'
 '24.03.2026' '15.06.2026' '01.01.2026' '18.06.2026' '27.06.2026'
 '08.03.2026' '19.06.2026' '13.04.2026' '18.05.2026' '26.04.2026'
 '11.01.2026' '11.05.2026' '30.03.2026' '09.01.2026' '30.05.2026']
----------------------------------------
wg_typ
['gemischt' 'Studenten-WG' 'Frauen-WG' 'Männer-WG' 'Berufstätigen-WG']
----------------------------------------
year_built
[1900 1921 1976 2008 1991 2011 1942 2022 1996 1925 1903 1934 1974 1922
 1950 1969 1941 1979 1948 1914 2000 2017 1917 1963 1904 2014 1955 2024
 1958 1949 1935 2001 2018 2009 2005 1924 1907 1975 1965 1954 1993 1978
 2004 1913 1928 1985 1984 1997 1962 1966 1911 1952 1981 1936 1920 2003
 1998 2012 1953 2002 1983 1945 1939 1982 2010 1910 1995 1968 1926 1959
 2006 1905 1980 1956 1929 2016 1940 1961 1933 1919 1902 1988 1986 1992
 1916 1967 1951 1960 2019 1994 1912 1927 1901 1943 1946 1931 2007 1930
 1957 1964 2013 1989 1932 1938 1918 1972 1987 1923 2020 1947 2021 1908
 2023 1973 2015 1970 1944 1937 1906 1999 1977 1909 1915 1990 1971]
----------------------------------------
priority_score
[ 7  9  5  6  4  8 10  1  3  2]
----------------------------------------
num_rooms
[3.  2.  1.  1.5 2.5]
----------------------------------------
plz
[93051 93055 93053 93059 93049 93047]
----------------------------------------
balcony
['nein' 'ja']
----------------------------------------
days_online
[52 71 40 23 51  7 61 18 81 80 76 50 24 59  4 83 46 30  5 22 87 13 25 44
 14 20 21 86 65 34 64  1 41 55 39 60 67 16 58 11 26 42 74 62  6 43  9 63
  2 47 89 53 12 57 75 78 28 37 82  8 38 29 73 84 69 19 72  3 88 36 90 54
 35 31 15 33 68 17 70 48 45 49 27 10 79 85 77 66 56 32]
----------------------------------------
living_area_m2
[21.2 18.8 16.3 20.4 22.5 20.6 17.7 21.7 15.1 16.7 17.8 21.  13.5 22.1
 15.2 15.6 34.  23.4 22.7 26.6 24.6 19.3 13.9 21.9 28.  22.9 12.4 20.1
 11.8 22.4 26.3 20.8 22.  12.2 11.5 23.1 20.  19.8 18.3 14.7 14.8 22.3
 19.7 18.7 12.9 14.9 20.2 24.2 20.3 15.3 15.  30.4 19.2 26.7 25.  21.1
 16.  16.4 27.9 15.7 31.  13.7 13.3 18.2 13.4 18.6 25.2 21.5 16.1 12.8
 21.6 16.8 19.5 16.5 16.9 18.9 23.9 14.6 14.3 31.3 11.  25.4 20.7 19.4
 25.9 17.4 33.8 31.7 28.2 27.4 24.5 12.7 17.9 14.4 14.1 16.6 20.9 23.5
 11.2 26.8 17.3 18.5 18.  27.  27.6 13.  27.2 27.5 26.4 15.8 28.3 25.7
 29.7 18.1 21.4 25.8 25.5 12.5 22.8 26.1 20.5 13.8 29.6 15.4 30.  14.
 13.2 25.3 23.2 17.1 27.1 23.6 34.7 22.6 26.9 19.9 19.1 19.  23.7 11.4
 18.4 30.7 23.8 23.  12.3 15.9 26.2 13.6 19.6 17.5 24.8 17.2 12.6 30.6
 31.1 22.2 17.6 31.9 17.  11.7 21.8 32.9 27.8 11.9 21.3 30.2 28.5 15.5
 28.6 34.3 11.6 24.9 11.3 33.1 26.5 16.2 26.  12.  24.1 27.7 29.  31.6
 29.3 29.1 23.3 13.1 14.5 29.9 30.5 32.  12.1 32.2 29.8 10.5 33.2 28.1
 25.1 30.1 10.4 28.4 28.9 24.4 10.9 33.6 31.8 29.4 10.7 29.2 10.6 25.6
 14.2 31.5 31.2 24.7 10.8 28.8 34.4 34.8 27.3 30.8 24.3 32.7 30.9 32.8]
----------------------------------------
stadtteil
['Königswiesen' 'Burgweinting' 'Galgenberg' 'Stadtamhof' 'Karthaus-Prüll'
 'Dechbetten' 'Reinhausen' 'Kasernenviertel' 'Westenviertel' 'Innenstadt'
 'Kumpfmühl' 'Ziegetsdorf' 'Großprüfening' 'Ostenviertel']
----------------------------------------
living_area_text
['21.2 m2' '18.8 m2' '16.3 m2' '20,4 qm' '22 m²' '20.6 m2' '18 m²'
 '21,7 qm' '15 m²' '16,7 qm' '17,8 qm' '21 m²' '13.5 m2' '22,1 qm'
 '15,6 qm' '34,0 qm' '23 m²' '22,7 qm' '26.6 m2' '24,6 qm' '19.3 m2'
 '13,9 qm' '28,0 qm' '22,9 qm' '12,4 qm' '20.1 m2' '11.8 m2' '22,4 qm'
 '26.3 m2' '22.0 m2' '12.2 m2' '11,5 qm' '23,1 qm' '20,0 qm' '19,8 qm'
 '18,3 qm' '14,7 qm' '24.6 m2' '20 m²' '19 m²' '22,3 qm' '13 m²' '14,9 qm'
 '23,4 qm' '24,2 qm' '20.3 m2' '17,7 qm' '15,3 qm' '30 m²' '20.4 m2'
 '19.2 m2' '26,7 qm' '25 m²' '21,1 qm' '16 m²' '16.4 m2' '27.9 m2'
 '31.0 m2' '21.7 m2' '14 m²' '19,3 qm' '15.6 m2' '16,0 qm' '18,2 qm'
 '18,6 qm' '21.5 m2' '12.8 m2' '21,6 qm' '16.8 m2' '19.5 m2' '16.5 m2'
 '16.0 m2' '16.9 m2' '23.9 m2' '14,6 qm' '14.3 m2' '15.7 m2' '20.0 m2'
 '28.0 m2' '31,3 qm' '11 m²' '25.4 m2' '20,7 qm' '19,4 qm' '25,9 qm'
 '17.4 m2' '28 m²' '34 m²' '19,7 qm' '25,4 qm' '32 m²' '14.7 m2' '27,4 qm'
 '24 m²' '12,7 qm' '31,0 qm' '12.4 m2' '13.9 m2' '14,4 qm' '14.1 m2'
 '16.6 m2' '18.9 m2' '15,0 qm' '14.8 m2' '18.7 m2' '11.2 m2' '27 m²'
 '16,6 qm' '17,3 qm' '16,3 qm' '27,6 qm' '13.0 m2' '16,5 qm' '27.2 m2'
 '26,4 qm' '15,8 qm' '28.3 m2' '25.7 m2' '29.7 m2' '18,1 qm' '21,4 qm'
 '15.1 m2' '26 m²' '17,4 qm' '25,5 qm' '20,3 qm' '22.9 m2' '12,5 qm'
 '16.7 m2' '16,1 qm' '21,2 qm' '19.7 m2' '26.7 m2' '26,8 qm' '13.8 m2'
 '29,6 qm' '15,4 qm' '30,0 qm' '14,0 qm' '13.2 m2' '25.3 m2' '25,2 qm'
 '23.2 m2' '16,4 qm' '17 m²' '33.8 m2' '14,3 qm' '25.2 m2' '17,1 qm'
 '23.6 m2' '34,7 qm' '24.5 m2' '18,5 qm' '22,6 qm' '18.3 m2' '15.8 m2'
 '20,1 qm' '19,9 qm' '19,1 qm' '22,0 qm' '19,0 qm' '23,7 qm' '20.9 m2'
 '27.6 m2' '11,4 qm' '31 m²' '18,7 qm' '12 m²' '16,9 qm' '23,8 qm'
 '19.8 m2' '23.0 m2' '23.4 m2' '20.2 m2' '20.5 m2' '29,7 qm' '27.1 m2'
 '13.6 m2' '20,6 qm' '19.1 m2' '17.1 m2' '18.5 m2' '22.4 m2' '26.4 m2'
 '12,3 qm' '13,5 qm' '22.5 m2' '25,3 qm' '31.1 m2' '17.6 m2' '15.2 m2'
 '17.0 m2' '17,0 qm' '17,9 qm' '16.1 m2' '20,8 qm' '11,7 qm' '21,8 qm'
 '32,9 qm' '26,1 qm' '11.9 m2' '21.1 m2' '19.9 m2' '23.5 m2' '18.4 m2'
 '12,9 qm' '17,2 qm' '30,2 qm' '24,5 qm' '15.9 m2' '23,6 qm' '22,5 qm'
 '30.7 m2' '21,9 qm' '18.6 m2' '35 m²' '27,1 qm' '17,5 qm' '28.6 m2'
 '20.8 m2' '34,3 qm' '21,5 qm' '17.2 m2' '30,6 qm' '15.5 m2' '14,1 qm'
 '23,5 qm' '15,2 qm' '23.1 m2' '26,6 qm' '14.6 m2' '21.3 m2' '18.0 m2'
 '33,1 qm' '21.9 m2' '25,7 qm' '23,9 qm' '23.7 m2' '26.5 m2' '30.2 m2'
 '24,8 qm' '26,9 qm' '16,2 qm' '26,0 qm' '13,7 qm' '18,8 qm' '27,0 qm'
 '19,2 qm' '20.7 m2' '28,6 qm' '21,3 qm' '21.0 m2' '23,0 qm' '20,2 qm'
 '27.7 m2' '29.0 m2' '31,6 qm' '13.4 m2' '29,3 qm' '11,0 qm' '27.4 m2'
 '29,1 qm' '22,8 qm' '15.3 m2' '16.2 m2' '23.3 m2' '13,3 qm' '25.5 m2'
 '13,1 qm' '27,2 qm' '26.0 m2' '21.6 m2' '15,7 qm' '17.3 m2' '30.4 m2'
 '31,1 qm' '18.2 m2' '17.8 m2' '15.4 m2' '19.6 m2' '23,3 qm' '27.0 m2'
 '23.8 m2' '29.9 m2' '31,7 qm' '19.0 m2' '32.0 m2' '18,0 qm' '32,2 qm'
 '14.0 m2' '29,8 qm' '10 m²' '25.9 m2' '28.5 m2' '16,8 qm' '33 m²'
 '28,1 qm' '13,6 qm' '13.7 m2' '24.8 m2' '29 m²' '30.1 m2' '19,5 qm'
 '18,9 qm' '28.4 m2' '11,2 qm' '21,0 qm' '24.4 m2' '28,2 qm' '14.5 m2'
 '22.3 m2' '33.6 m2' '22.1 m2' '31,8 qm' '26.9 m2' '28.9 m2' '26.1 m2'
 '24,9 qm' '29,4 qm' '21.8 m2' '17.9 m2' '27,5 qm' '10.6 m2' '22.2 m2'
 '26,5 qm' '19,6 qm' '33.2 m2' '22,2 qm' '17,6 qm' '26,3 qm' '20,5 qm'
 '14,5 qm' '26.2 m2' '17.5 m2' '12,2 qm' '28,3 qm' '13,4 qm' '29.4 m2'
 '19.4 m2' '22.7 m2' '24.9 m2' '31,2 qm' '21.4 m2' '25,8 qm' '23,2 qm'
 '25.6 m2' '25,6 qm' '24,4 qm' '14.4 m2' '24.2 m2' '15,5 qm' '28.1 m2'
 '28,5 qm' '18,4 qm' '10,6 qm' '27.8 m2' '26,2 qm' '12.1 m2' '24,7 qm'
 '13.3 m2' '11.4 m2' '25,0 qm' '10,8 qm' '15.0 m2' '20,9 qm' '13.1 m2'
 '15,9 qm' '25.1 m2' '34.7 m2' '18.1 m2' '29,9 qm' '33,6 qm' '34.4 m2'
 '32.2 m2' '34.8 m2' '28,9 qm' '27,9 qm' '30,8 qm' '13,8 qm' '14.2 m2'
 '22.8 m2' '25,1 qm' '24,3 qm' '12.6 m2' '29.3 m2' '24.1 m2' '32,7 qm'
 '28.2 m2' '10,9 qm' '27,3 qm' '13,0 qm' '29,0 qm' '11.7 m2' '32.8 m2']
----------------------------------------
energieausweis
['A+' 'E' 'D' 'A' 'B' 'G' 'F' 'C' 'H']
----------------------------------------
dist_uni_km
[ 7.5 10.8 10.7 10.9  9.4  1.8  3.4  4.3  6.2  8.6  3.7  1.7  2.4 10.1
 10.6  9.1  9.8  4.7  8.   9.5  4.6 11.1  5.   2.5  8.4  7.2 10.5  8.1
  4.9  4.5  9.3  6.   1.4  6.9 10.   9.9  9.6  1.1  7.   4.2  4.8  6.7
  7.7  7.4  2.2  8.7  1.2  7.6  6.3  4.4  2.7  1.5  6.1  8.9  2.9  5.7
  7.9  5.8  3.8  7.8  3.6  2.1  6.4  1.   6.8  4.1  5.2  6.6 11.   2.3
  5.6  3.1  9.  10.3  5.4  3.9  8.8  2.   3.2  0.9  5.1  6.5 11.4 10.4
 10.2 11.2  7.1  2.8  8.5  1.6  8.3  4.   5.5  9.2  5.9  9.7  8.2  3.3
  3.   7.3  5.3  2.6  3.5  1.9 11.5 11.3 11.6  1.3]
----------------------------------------
contact_type
['Genossenschaft' 'Makler' 'Privat']
----------------------------------------
heating_type
['Nachtspeicher' 'Gasetagenheizung' 'Fernwärme' 'Zentralheizung' 'Öl'
 'Pellet']
----------------------------------------
kitchen
['Pantry' 'Einbauküche' 'keine']
----------------------------------------
dist_uni_min
[30 44 43 37  7 14 17 24 35 15 11 41 42 39 19 32 38 18 20 10 33 29 36  6
 27 40  5 28 25  9 31 23 26 13  8 34 21 16 22 12 45]
----------------------------------------
elevator
['ja' 'nein']
----------------------------------------
clicks_last_week
[211  52  65 227  94 114 125 220 185 297 245  93  98 237 128 280  42 206
 138 122  31 110 155 181   9  24  89  18 130 275  22 202 299 123 251 140
 153 198 248 235 279  57 177 259 160 264 194 135 203 217 113 212  12  19
 149 208 191 169 180  56   8 103 239 229 141 107 116   7  21 230 265 242
 173 204 117 266 187 226 278 131 243  95  44  88 221 171  79  51   0 215
  36  14 247  15 287  48 193 241  77  69  87  62 158 109 263 276  30 285
 271 105  28 104 256 118 255  63   1  23 124 132 284 179 192 272  49  72
 182 197 186 207  59  50 195 152  16 216  41 273  96 165 129 142 161  82
  92 293  40 290  54 267 170  27   6 201 151 115 134  70 258 238 108 175
  66 159 277 143 167  73 190  43 292 183  85  34  53 300 168   3  33 218
 252 174 162  46 106 234  78 139 246 249  84 178 156 120  81 269  90 291
 127 200 281 262  86  29  55 172  39 257  17 240 210  76  26 133   4  91
  32  37 295 224  74 188 250 294  38  67 112 274 148 254 286 222 253 121
 119 145 213 189 126  61 289 228 244 166 231 214 288 147  60 137 136 163
 176 268 298  10  11 236  20   2 146 233 150 101  13 199 223  47  45 219
 164 209 205 102  68 225  99 260  83 270  35  80 196 184 296 261 232  97
  25   5 157 100 111 282 154  71 144  75  58  64]
----------------------------------------
listing_id
['INS-2026-49534' 'INS-2026-39524' 'INS-2026-45414' ... 'INS-2026-24228'
 'INS-2026-33925' 'INS-2026-38990']
----------------------------------------
nebenkosten_eur
[ 57 126 157 164 149  83  74  85 132 103  56 150  98 162 128 110  93 178
 108 112 102 123 100 134  73  58 153  76 125  63 163 117  50  70  68 116
 142  99  49 144  65  91  55  78  62  97 139 129 145 175 107  66 101  88
  81 113  87 148 187 118  77 141 119 161  72  84  92 111 127 138 199 124
 166  82 147  46 136  60 109 131  86  59 167 190 105 133 197  71 185  67
  94  95  90  89  54 135  75  80  61 140 120 159  79 152 151  64 181  96
 173 114 143  52 121 154 160  45 115 189 104 122  48 170 186 168 171 137
 203  53  69 155 146 106 169 182 179 174 156 180  40 158 165 176 194  47
  51 201 130 183  39 202 172]
----------------------------------------

### define cleaning functions

In [7]:
def drop_unleidige_columns(df: pd.DataFrame, cols_to_be_dropped: list) -> pd.DataFrame:
    # print("entferne unleidige Spalten")
    df=df.drop(cols_to_be_dropped, axis=1)
    return df


def mapping_floor_and_add_col_is_dachgeschoss(df: pd.DataFrame) -> pd.DataFrame:
    # print("schreibe floor in ordinal um und füge spalte is_dachgeschoss hinzu")
    df["is_dachgeschoss"] = df["floor"] == "DG"
   
    df["floor_num"] = df["floor"].map({
                                        "Souterrain": -1,
                                        "EG": 0,
                                        "1. OG": 1,
                                        "2. OG": 2,
                                        "3. OG": 3,
                                        "4. OG": 4
                                    })
    #DG ist special
    df.loc[df["floor"] == "DG", "floor_num"] = df["total_floors"]
    df["floor_num"] = df["floor_num"].astype(int)

    df = df.drop(["floor"], axis=1)
    return df

    
def clean_kaltmiete_listing(df: pd.DataFrame) -> pd.DataFrame:
    # print("Bereinige Kaltmiete_listing")
    df['kaltmiete_listing'] = (
        df['kaltmiete_listing'].str.replace('€', '', regex=False)
                                .str.replace('EUR', '', regex=False)
                                .str.replace(',00', '', regex=False)
                                .str.replace('kalt', '', regex=False)
                                .str.replace('Kaltmiete:', '', regex=False)
                                .str.replace(' ', '', regex=False)
                                .str.strip()
                              )
    #nebenkosten rausrechnen
    df["ist_warm"] = df["kaltmiete_listing"].str.contains("warm", na=False) #nur zur kontrolle
    df["kaltmiete_vorher"] = df["kaltmiete_listing"] #nur zur kontrolle
    mask = df["kaltmiete_listing"].str.contains("warm", na=False)
    df.loc[mask, "kaltmiete_listing"] = (
        df.loc[mask, "kaltmiete_listing"]
            .str.replace("warm", "", regex=False)
            .astype(int)
            - df.loc[mask, "nebenkosten_eur"]
    )

    #in Zahl umwandeln
    df["kaltmiete_listing"] = (
        pd.to_numeric(df["kaltmiete_listing"], errors="coerce")
            .fillna(0)
            .astype(int)
    )
    return df


def qm_preis_berechnen(df: pd.DataFrame) -> pd.DataFrame:
    # print("Berechnet qm Preise")
    df["kaltmiete_qm"] = df["kaltmiete_listing"] / df["living_area_m2"]
    return df


def drop_absurde_qm_preise(df:pd.DataFrame, min=0, max=100) -> pd.DataFrame:
    # print(f"Entferne preis/qm outlier, mindestpreis= {min}, höchstpreis={max}")
    # print(f"{len(df)} Einträge im df")
    # print(f"droppe {len(df[df["kaltmiete_qm"] <= min])} Einträge weil qm preis <={min}")
    # print(f"droppe {len(df[df["kaltmiete_qm"] >= max])} Einträge weil qm preis >={max}")
    df = df[df["kaltmiete_qm"] >= min]
    df = df[df["kaltmiete_qm"] <= max]
    # print(f"{len(df)} Einträge im df")
    return df


def mapping(df:pd.DataFrame) -> pd.DataFrame:
    # print("mappe balcony, energieausweis,elevator")
    df["balcony"] = df["balcony"].map({"ja": True, "nein": False})
    df["energieausweis"] = df["energieausweis"].map({"A+": 8,
                                                    "A": 7,
                                                    "B": 6,
                                                    "C": 5,
                                                    "D": 4,
                                                    "E": 3,
                                                    "F": 2,
                                                    "G": 1,
                                                    "H": 0})
    df["elevator"] = df["elevator"].map({"ja": True, "nein": False})
    df["furnished"] = df["furnished"].map({"unmöbliert": 0, "teilmöbliert": 1, "möbliert": 2})
    return df


def plz_als_str(df:pd.DataFrame) -> pd.DataFrame:
    # print("plz als string")
    df["plz"] = df["plz"].astype(str) #PLZ sind keine echten Zahlen, sondern IDs für Regionen.als Kategorie encoden
    return df


def drop_helfer_spalten(df:pd.DataFrame):
    # print("droppe helferspalten")
    df = df.drop(["kaltmiete_vorher", "ist_warm", "kaltmiete_qm"], axis=1)
    return df


def add_room_size_m2(df:pd.DataFrame) -> pd.DataFrame:
    df["room_size_m2"] = df["living_area_m2"] / df["num_rooms"].replace(0, 1)
    return df


def add_luxury_score(df:pd.DataFrame) -> pd.DataFrame:
    df["luxury_score"] = (
        df["balcony"].astype(int) + 
        df["elevator"].astype(int) + 
        (df["kitchen"] == "Einbauküche").astype(int)
    )
    return df


def add_high_floor_without_elevator_penalty(df:pd.DataFrame) -> pd.DataFrame:
    df["high_floor_no_elevator"] = ((df["floor_num"] >= 3) & (~df["elevator"])).astype(int)
    return df
    

def add_student_uni_penalty(df:pd.DataFrame) -> pd.DataFrame:
    df["student_uni_penalty"] = (df["wg_typ"] == "Studenten-WG").astype(int) * df["dist_uni_min"]
    return df

In [8]:
def clean_me_pd(df:pd.DataFrame, is_train=False) -> pd.DataFrame:
    df = mapping_floor_and_add_col_is_dachgeschoss(df)
    if is_train:
        df = clean_kaltmiete_listing(df)
        df = qm_preis_berechnen(df)
        df = drop_absurde_qm_preise(df,8,35)
        df = drop_helfer_spalten(df)
    df = mapping(df)
    df = plz_als_str(df)
    df = add_room_size_m2(df)
    df = add_luxury_score(df)
    df = add_high_floor_without_elevator_penalty(df)
    df = add_student_uni_penalty(df)
    df = drop_unleidige_columns(df, ["listing_id", "living_area_text","days_online","year_built","listing_date", "num_photos", "priority_score","clicks_last_week","nebenkosten_eur", "balcony"])

    return df

In [9]:
pd_cleaned_data = clean_me_pd(train_original.copy(), is_train=True)
display(train_original.head(10))
display(pd_cleaned_data.head(10))

,kaltmiete_listing,overpriced,floor,furnished,num_photos,total_floors,building_age_years,listing_date,wg_typ,year_built,priority_score,num_rooms,plz,balcony,days_online,living_area_m2,stadtteil,living_area_text,energieausweis,dist_uni_km,contact_type,heating_type,kitchen,dist_uni_min,elevator,clicks_last_week,listing_id,nebenkosten_eur
0,325 €,False,2. OG,teilmöbliert,16,2,126,08.05.2026,gemischt,1900,7,3.0,93051,nein,52,21.2,Königswiesen,21.2 m2,A+,7.5,Genossenschaft,Nachtspeicher,Pantry,30,ja,211,INS-2026-49534,57
1,335 €,True,3. OG,möbliert,10,2,105,04.04.2026,gemischt,1921,9,2.0,93055,ja,71,18.8,Burgweinting,18.8 m2,A+,10.8,Makler,Gasetagenheizung,Einbauküche,44,nein,52,INS-2026-39524,126
2,491 warm,False,EG,unmöbliert,10,2,50,18.03.2026,Studenten-WG,1976,5,1.0,93053,ja,40,16.3,Galgenberg,16.3 m2,E,10.7,Privat,Gasetagenheizung,Einbauküche,43,nein,65,INS-2026-45414,157
3,373 €,False,2. OG,unmöbliert,10,2,18,19.04.2026,Studenten-WG,2008,6,3.0,93059,nein,23,20.4,Stadtamhof,"20,4 qm",E,10.9,Privat,Fernwärme,Einbauküche,44,nein,227,INS-2026-36290,164
4,328,False,EG,teilmöbliert,10,4,35,16.02.2026,Studenten-WG,1991,7,3.0,93049,nein,71,22.5,Karthaus-Prüll,22 m²,D,9.4,Privat,Zentralheizung,Einbauküche,37,nein,94,INS-2026-68392,149
5,"301,00 EUR",True,Souterrain,teilmöbliert,21,1,15,22.05.2026,Frauen-WG,2011,4,2.0,93051,ja,51,20.6,Dechbetten,20.6 m2,A+,1.8,Privat,Nachtspeicher,Pantry,7,ja,114,INS-2026-90560,83
6,339,True,DG,unmöbliert,14,2,84,04.01.2026,Frauen-WG,1942,8,2.0,93059,ja,7,17.7,Reinhausen,18 m²,A+,3.4,Makler,Öl,Einbauküche,14,ja,125,INS-2026-87234,74
7,467 warm,False,DG,unmöbliert,15,2,4,13.02.2026,gemischt,2022,8,3.0,93053,nein,52,21.7,Kasernenviertel,"21,7 qm",D,4.3,Privat,Gasetagenheizung,Einbauküche,17,nein,220,INS-2026-90121,85
8,345 warm,False,DG,unmöbliert,6,2,30,17.02.2026,Männer-WG,1996,10,3.0,93055,nein,61,15.1,Burgweinting,15 m²,D,6.2,Privat,Gasetagenheizung,Pantry,24,ja,185,INS-2026-70439,132
9,306 €,False,2. OG,unmöbliert,8,4,101,22.04.2026,Frauen-WG,1925,7,1.0,93049,nein,18,17.7,Westenviertel,18 m²,A,8.6,Privat,Gasetagenheizung,keine,35,nein,297,INS-2026-92509,103

,kaltmiete_listing,overpriced,furnished,total_floors,building_age_years,wg_typ,num_rooms,plz,living_area_m2,stadtteil,energieausweis,dist_uni_km,contact_type,heating_type,kitchen,dist_uni_min,elevator,is_dachgeschoss,floor_num,room_size_m2,luxury_score,high_floor_no_elevator,student_uni_penalty
0,325,False,1,2,126,gemischt,3.0,93051,21.2,Königswiesen,8,7.5,Genossenschaft,Nachtspeicher,Pantry,30,True,False,2,7.066667,1,0,0
1,335,True,2,2,105,gemischt,2.0,93055,18.8,Burgweinting,8,10.8,Makler,Gasetagenheizung,Einbauküche,44,False,False,3,9.400000,2,1,0
2,334,False,0,2,50,Studenten-WG,1.0,93053,16.3,Galgenberg,3,10.7,Privat,Gasetagenheizung,Einbauküche,43,False,False,0,16.300000,2,0,43
3,373,False,0,2,18,Studenten-WG,3.0,93059,20.4,Stadtamhof,3,10.9,Privat,Fernwärme,Einbauküche,44,False,False,2,6.800000,1,0,44
4,328,False,1,4,35,Studenten-WG,3.0,93049,22.5,Karthaus-Prüll,4,9.4,Privat,Zentralheizung,Einbauküche,37,False,False,0,7.500000,1,0,37
5,301,True,1,1,15,Frauen-WG,2.0,93051,20.6,Dechbetten,8,1.8,Privat,Nachtspeicher,Pantry,7,True,False,-1,10.300000,2,0,0
6,339,True,0,2,84,Frauen-WG,2.0,93059,17.7,Reinhausen,8,3.4,Makler,Öl,Einbauküche,14,True,True,2,8.850000,3,0,0
7,382,False,0,2,4,gemischt,3.0,93053,21.7,Kasernenviertel,4,4.3,Privat,Gasetagenheizung,Einbauküche,17,False,True,2,7.233333,1,0,0
8,213,False,0,2,30,Männer-WG,3.0,93055,15.1,Burgweinting,4,6.2,Privat,Gasetagenheizung,Pantry,24,True,True,2,5.033333,1,0,0
9,306,False,0,4,101,Frauen-WG,1.0,93049,17.7,Westenviertel,7,8.6,Privat,Gasetagenheizung,keine,35,False,False,2,17.700000,0,0,0

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

def get_scikit_preprocessor():
    categorical_features = ["wg_typ", "plz", "stadtteil", "contact_type", "heating_type", "kitchen"]
    # Alle Spalten, die kontinuierliche Zahlenwerte oder ordinale Werte (wie floor_num) enthalten
    numeric_features = [
        "total_floors", "building_age_years", "num_rooms", 
        "living_area_m2", "dist_uni_km", "dist_uni_min", 
        "floor_num", "furnished", "room_size_m2",
        "luxury_score", "high_floor_no_elevator", "student_uni_penalty"
    ]
    
    preprocessor = ColumnTransformer(
        transformers=[
            ("num", StandardScaler(), numeric_features),
            ("cat", OneHotEncoder(sparse_output=False, handle_unknown='ignore'), categorical_features)
        ],
        remainder="passthrough" # Lässt Booleans wie 'balcony' und 'elevator' unverändert durch
    )
    return preprocessor

# machine learning approach

In [11]:
train = train_original.copy()
train = clean_me_pd(train, is_train=True)
preprocessor = get_scikit_preprocessor()

In [12]:
X = train.drop(["kaltmiete_listing", "overpriced"], axis=1)
y_reg = train["kaltmiete_listing"]
y_class = train["overpriced"]

### regression

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.pipeline import Pipeline
from scipy.stats import randint, uniform
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV

In [14]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y_reg, test_size=0.2, random_state=42)

#### find optimal hyperparams with RandomSearchGV

In [15]:
xgb_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(random_state=42, n_jobs=-1))
])

param_dist_xgb = {
    'model__n_estimators': randint(100, 800),
    'model__learning_rate': uniform(0.01, 0.29), # 0.01 bis 0.3
    'model__max_depth': randint(3, 10),
    'model__subsample': uniform(0.5, 0.5),       # 0.5 bis 1.0 (wie viele Datenpunkte pro Baum)
    'model__colsample_bytree': uniform(0.5, 0.5) # 0.5 bis 1.0 (wie viele Features pro Baum)
}

random_search_xgb = RandomizedSearchCV(
    xgb_pipeline, 
    param_distributions=param_dist_xgb, 
    n_iter=50, 
    cv=10, 
    scoring='r2', 
    n_jobs=-1,
    random_state=42
)

random_search_xgb.fit(X_train, y_train)

y_pred_xgb = random_search_xgb.best_estimator_.predict(X_valid)
score_xgb = r2_score(y_valid, y_pred_xgb)

print(f"Beste Parameter XGBoost: {random_search_xgb.best_params_}")
print(f"R2 Score: {score_xgb:.4f}") # 0.9311

Beste Parameter XGBoost: {'model__colsample_bytree': 0.5165253664502742, 'model__learning_rate': 0.11007066192773805, 'model__max_depth': 3, 'model__n_estimators': 502, 'model__subsample': 0.8403527257773834}
R2 Score: 0.9311

#### optimal hyperparams

In [16]:
XGB_reg_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(colsample_bytree=0.5165253664502742, learning_rate=0.11007066192773805, max_depth=3, n_estimators=502, subsample=0.8403527257773834))
])


X_train, X_valid, y_train, y_valid = train_test_split(X, y_reg, test_size=0.2, random_state=42)

XGB_reg_pipeline.fit(X_train, y_train)

y_pred = XGB_reg_pipeline.predict(X_valid)

score = r2_score(y_valid, y_pred)
print(f"R2 Score: {score:.4f}") # 0.9332

R2 Score: 0.9332

#### predict test data

In [17]:
def check_file_regression(file_path):
    """Check that a regression-prediction CSV is valid for submission to Task 1."""
    try:
        predictions = pd.read_csv(file_path)
    except FileNotFoundError:
        print("File not found or could not be loaded.")
        return False
    if predictions.shape[0] != 500:
        print(f"Expected 500 rows, got {predictions.shape[0]}.")
        return False
    if predictions.shape[1] != 1:
        print("The file should contain exactly one column.")
        return False
    if predictions.columns[0] != "kaltmiete":
        print("The column name should be 'kaltmiete'.")
        return False
    if not np.issubdtype(predictions["kaltmiete"].dtype, np.number):
        print("The values in the 'kaltmiete' column should be numeric.")
        return False
    print("The file is a valid submission for Task 1.")
    return True

In [18]:
test = test_original.copy()

X_test = clean_me_pd(test, is_train=False)

XGB_reg_pipeline.fit(X, y_reg) # Noch einmal auf allen Daten trainieren für maximale Power
final_predictions = XGB_reg_pipeline.predict(X_test)

submission_df = pd.DataFrame({
    "kaltmiete": final_predictions
})

submission_filename = "kaltmiete_prediction.csv"
submission_df.to_csv(submission_filename, index=False)
print(f"Datei '{submission_filename}' erfolgreich gespeichert!")

check_file_regression(submission_filename)

Datei 'kaltmiete_prediction.csv' erfolgreich gespeichert!
The file is a valid submission for Task 1.

True