In [8]:
import numpy as np
import pandas as pd

In [9]:
train_original = pd.read_csv("data/train.csv")
test_original = pd.read_csv("data/test.csv")

In [10]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [12]:
train_original.head()

,kaltmiete_listing,overpriced,floor,furnished,num_photos,total_floors,building_age_years,listing_date,wg_typ,year_built,priority_score,num_rooms,plz,balcony,days_online,living_area_m2,stadtteil,living_area_text,energieausweis,dist_uni_km,contact_type,heating_type,kitchen,dist_uni_min,elevator,clicks_last_week,listing_id,nebenkosten_eur
0,325 €,False,2. OG,teilmöbliert,16,2,126,08.05.2026,gemischt,1900,7,3.0,93051,nein,52,21.2,Königswiesen,21.2 m2,A+,7.5,Genossenschaft,Nachtspeicher,Pantry,30,ja,211,INS-2026-49534,57
1,335 €,True,3. OG,möbliert,10,2,105,04.04.2026,gemischt,1921,9,2.0,93055,ja,71,18.8,Burgweinting,18.8 m2,A+,10.8,Makler,Gasetagenheizung,Einbauküche,44,nein,52,INS-2026-39524,126
2,491 warm,False,EG,unmöbliert,10,2,50,18.03.2026,Studenten-WG,1976,5,1.0,93053,ja,40,16.3,Galgenberg,16.3 m2,E,10.7,Privat,Gasetagenheizung,Einbauküche,43,nein,65,INS-2026-45414,157
3,373 €,False,2. OG,unmöbliert,10,2,18,19.04.2026,Studenten-WG,2008,6,3.0,93059,nein,23,20.4,Stadtamhof,"20,4 qm",E,10.9,Privat,Fernwärme,Einbauküche,44,nein,227,INS-2026-36290,164
4,328,False,EG,teilmöbliert,10,4,35,16.02.2026,Studenten-WG,1991,7,3.0,93049,nein,71,22.5,Karthaus-Prüll,22 m²,D,9.4,Privat,Zentralheizung,Einbauküche,37,nein,94,INS-2026-68392,149

In [13]:
print(train_original.columns)
print(test_original.columns)
print(train_original.dtypes)
print(test_original.dtypes)

Index(['kaltmiete_listing', 'overpriced', 'floor', 'furnished', 'num_photos',
       'total_floors', 'building_age_years', 'listing_date', 'wg_typ',
       'year_built', 'priority_score', 'num_rooms', 'plz', 'balcony',
       'days_online', 'living_area_m2', 'stadtteil', 'living_area_text',
       'energieausweis', 'dist_uni_km', 'contact_type', 'heating_type',
       'kitchen', 'dist_uni_min', 'elevator', 'clicks_last_week', 'listing_id',
       'nebenkosten_eur'],
      dtype='object')
Index(['floor', 'furnished', 'num_photos', 'total_floors',
       'building_age_years', 'listing_date', 'wg_typ', 'year_built',
       'priority_score', 'num_rooms', 'plz', 'balcony', 'days_online',
       'living_area_m2', 'stadtteil', 'living_area_text', 'energieausweis',
       'dist_uni_km', 'contact_type', 'heating_type', 'kitchen',
       'dist_uni_min', 'elevator', 'clicks_last_week', 'listing_id',
       'nebenkosten_eur'],
      dtype='object')
kaltmiete_listing      object
overpriced               bool
floor                  object
furnished              object
num_photos              int64
total_floors            int64
building_age_years      int64
listing_date           object
wg_typ                 object
year_built              int64
priority_score          int64
num_rooms             float64
plz                     int64
balcony                object
days_online             int64
living_area_m2        float64
stadtteil              object
living_area_text       object
energieausweis         object
dist_uni_km           float64
contact_type           object
heating_type           object
kitchen                object
dist_uni_min            int64
elevator               object
clicks_last_week        int64
listing_id             object
nebenkosten_eur         int64
dtype: object
floor                  object
furnished              object
num_photos              int64
total_floors            int64
building_age_years      int64
listing_date           object
wg_typ                 object
year_built              int64
priority_score          int64
num_rooms             float64
plz                     int64
balcony                object
days_online             int64
living_area_m2        float64
stadtteil              object
living_area_text       object
energieausweis         object
dist_uni_km           float64
contact_type           object
heating_type           object
kitchen                object
dist_uni_min            int64
elevator               object
clicks_last_week        int64
listing_id             object
nebenkosten_eur         int64
dtype: object

In [14]:
#data cleaning

In [15]:


for col in train_original.columns:
    print("-" * 40)
    print(col)
    print(train_original[col].unique())
    print("-" * 40)

#kaltmiete_listing - muss preprocessed werden
#overpriced ist sauber
#floor kann gemapped werden (von -1 bis 5) - weitere spalte is_dachgeschoss[True,False] kann hinzugefügt werden zum trainieren
# furnished keine Ahnung ob man das ordinal machen sollte
#num_photos droppen
#total_floors wird behalten
#building_age_years wird behalten, ist besser als year_built
#listing_date droppen
#wg_typ wird behalten, denke nicht dass man das ordinal machen sollte
#year_built droppen
#priority_score - !!! Keine Ahnung was das ist!!!
#num_rooms wird behalten
#plz wird in String umgewandelt da es keine sinnvolle Ordnung als Zahl dafür gibt
#balcony wird in True/False umgewandelt
#days_online droppen
#living_area_m2 wird behalten, das ist sauber (wird mit benutzt um outlyer in den preis/qm zu droppen
#stadtteil wird behalten - evtl mit plz blabla doppelter einfluß
#living_area_text droppen, hab die values in der anderne Spalte
#energieausweis wird ordinal gemacht
#dist_uni_km wird behalten
#contact_type wird behalten
#heating_Type wird behalten
#kitchen wird behalten, ordinal machen könnte sinn machen aber nicht implementiert
#dist_uni_min wird behalten, ist ein bissl was anderes als dist_uni_km inmyopinion - aber vllt könnte man eins von beiden droppen
#elevator wird in True/False umgewandelt
#clicks_last_week wird behalten - könnte vorraussagen ob die miete für die qm preise attraktiv ist
#listing_id droppen
#nebenkosten_eur wird behalten


#ich kann listing_id, living_area_text, days_online,year_built listing_date, num_photos droppen
# besonders listing_id: enthält 10*2 Duplikat listing_ids, die wohnungen haben nichts miteinander zu tun

----------------------------------------
kaltmiete_listing
['325 €' '335 €' '491 warm' ... '290' '530' 'Kaltmiete: 305 €']
----------------------------------------
----------------------------------------
overpriced
[False  True]
----------------------------------------
----------------------------------------
floor
['2. OG' '3. OG' 'EG' 'Souterrain' 'DG' '4. OG' '1. OG']
----------------------------------------
----------------------------------------
furnished
['teilmöbliert' 'möbliert' 'unmöbliert']
----------------------------------------
----------------------------------------
num_photos
[16 10 21 14 15  6  8  7 19 18  5 12  2  4 23  9 11 25  3 13 24 17 20 22]
----------------------------------------
----------------------------------------
total_floors
[2 4 1 3 7 6 5]
----------------------------------------
----------------------------------------
building_age_years
[126 105  50  18  35  15  84   4  30 101 123  92  52 104  76  57  85  47
  78 112  26   9 109  63 122  12  71   2  68  77  91  25   8  17  21 102
 119  51  61  72  33  48  22 113  98  41  42  29  64  60 115  74  45  90
 106  23  28  14  73  24  43  81  87  44  16 116  31  58 100  67  20 121
  46  70  97  10  86  65  93 107 124  38  40  34 110  59  75  66   7  32
 114  99 125  83  80  95  19  96  69  62  13  37  94  88 108  54  39 103
   6  79   5 118   3  53  11  56  82  89 120  27  49 117 111  36  55]
----------------------------------------
----------------------------------------
listing_date
['08.05.2026' '04.04.2026' '18.03.2026' '19.04.2026' '16.02.2026'
 '22.05.2026' '04.01.2026' '13.02.2026' '17.02.2026' '22.04.2026'
 '14.02.2026' '18.04.2026' '19.03.2026' '21.01.2026' '12.05.2026'
 '02.05.2026' '18.01.2026' '15.03.2026' '20.02.2026' '22.01.2026'
 '22.06.2026' '08.01.2026' '11.06.2026' '17.01.2026' '29.04.2026'
 '12.03.2026' '14.01.2026' '29.06.2026' '15.04.2026' '03.05.2026'
 '31.03.2026' '09.04.2026' '16.03.2026' '04.05.2026' '31.01.2026'
 '09.06.2026' '11.03.2026' '25.05.2026' '28.04.2026' '17.04.2026'
 '25.01.2026' '06.05.2026' '22.03.2026' '04.02.2026' '15.02.2026'
 '21.05.2026' '13.03.2026' '05.01.2026' '02.02.2026' '06.02.2026'
 '12.04.2026' '10.01.2026' '10.06.2026' '28.01.2026' '07.02.2026'
 '08.02.2026' '05.04.2026' '16.06.2026' '24.06.2026' '09.02.2026'
 '16.04.2026' '28.03.2026' '01.06.2026' '10.03.2026' '15.01.2026'
 '12.01.2026' '01.02.2026' '24.02.2026' '24.05.2026' '07.06.2026'
 '21.04.2026' '29.03.2026' '23.05.2026' '04.06.2026' '14.03.2026'
 '02.01.2026' '16.05.2026' '11.02.2026' '12.02.2026' '31.05.2026'
 '19.01.2026' '19.02.2026' '23.03.2026' '25.06.2026' '13.05.2026'
 '10.02.2026' '23.04.2026' '26.03.2026' '10.05.2026' '07.01.2026'
 '07.05.2026' '21.03.2026' '12.06.2026' '22.02.2026' '24.01.2026'
 '30.01.2026' '28.05.2026' '14.06.2026' '09.03.2026' '20.01.2026'
 '27.01.2026' '19.05.2026' '17.06.2026' '06.01.2026' '07.04.2026'
 '27.03.2026' '06.03.2026' '10.04.2026' '25.03.2026' '02.04.2026'
 '17.05.2026' '02.03.2026' '29.05.2026' '28.06.2026' '21.02.2026'
 '08.06.2026' '11.04.2026' '14.05.2026' '17.03.2026' '03.06.2026'
 '05.02.2026' '23.06.2026' '01.05.2026' '03.01.2026' '27.05.2026'
 '07.03.2026' '26.01.2026' '01.03.2026' '02.06.2026' '01.04.2026'
 '28.02.2026' '03.03.2026' '04.03.2026' '03.02.2026' '23.02.2026'
 '27.02.2026' '18.02.2026' '20.05.2026' '26.06.2026' '27.04.2026'
 '26.02.2026' '05.06.2026' '20.06.2026' '26.05.2026' '20.04.2026'
 '24.04.2026' '16.01.2026' '03.04.2026' '25.02.2026' '05.03.2026'
 '20.03.2026' '06.04.2026' '06.06.2026' '13.01.2026' '21.06.2026'
 '29.01.2026' '15.05.2026' '23.01.2026' '09.05.2026' '08.04.2026'
 '30.04.2026' '14.04.2026' '13.06.2026' '05.05.2026' '25.04.2026'
 '24.03.2026' '15.06.2026' '01.01.2026' '18.06.2026' '27.06.2026'
 '08.03.2026' '19.06.2026' '13.04.2026' '18.05.2026' '26.04.2026'
 '11.01.2026' '11.05.2026' '30.03.2026' '09.01.2026' '30.05.2026']
----------------------------------------
----------------------------------------
wg_typ
['gemischt' 'Studenten-WG' 'Frauen-WG' 'Männer-WG' 'Berufstätigen-WG']
----------------------------------------
----------------------------------------
year_built
[1900 1921 1976 2008 1991 2011 1942 2022 1996 1925 1903 1934 1974 1922
 1950 1969 1941 1979 1948 1914 2000 2017 1917 1963 1904 2014 1955 2024
 1958 1949 1935 2001 2018 2009 2005 1924 1907 1975 1965 1954 1993 1978
 2004 1913 1928 1985 1984 1997 1962 1966 1911 1952 1981 1936 1920 2003
 1998 2012 1953 2002 1983 1945 1939 1982 2010 1910 1995 1968 1926 1959
 2006 1905 1980 1956 1929 2016 1940 1961 1933 1919 1902 1988 1986 1992
 1916 1967 1951 1960 2019 1994 1912 1927 1901 1943 1946 1931 2007 1930
 1957 1964 2013 1989 1932 1938 1918 1972 1987 1923 2020 1947 2021 1908
 2023 1973 2015 1970 1944 1937 1906 1999 1977 1909 1915 1990 1971]
----------------------------------------
----------------------------------------
priority_score
[ 7  9  5  6  4  8 10  1  3  2]
----------------------------------------
----------------------------------------
num_rooms
[3.  2.  1.  1.5 2.5]
----------------------------------------
----------------------------------------
plz
[93051 93055 93053 93059 93049 93047]
----------------------------------------
----------------------------------------
balcony
['nein' 'ja']
----------------------------------------
----------------------------------------
days_online
[52 71 40 23 51  7 61 18 81 80 76 50 24 59  4 83 46 30  5 22 87 13 25 44
 14 20 21 86 65 34 64  1 41 55 39 60 67 16 58 11 26 42 74 62  6 43  9 63
  2 47 89 53 12 57 75 78 28 37 82  8 38 29 73 84 69 19 72  3 88 36 90 54
 35 31 15 33 68 17 70 48 45 49 27 10 79 85 77 66 56 32]
----------------------------------------
----------------------------------------
living_area_m2
[21.2 18.8 16.3 20.4 22.5 20.6 17.7 21.7 15.1 16.7 17.8 21.  13.5 22.1
 15.2 15.6 34.  23.4 22.7 26.6 24.6 19.3 13.9 21.9 28.  22.9 12.4 20.1
 11.8 22.4 26.3 20.8 22.  12.2 11.5 23.1 20.  19.8 18.3 14.7 14.8 22.3
 19.7 18.7 12.9 14.9 20.2 24.2 20.3 15.3 15.  30.4 19.2 26.7 25.  21.1
 16.  16.4 27.9 15.7 31.  13.7 13.3 18.2 13.4 18.6 25.2 21.5 16.1 12.8
 21.6 16.8 19.5 16.5 16.9 18.9 23.9 14.6 14.3 31.3 11.  25.4 20.7 19.4
 25.9 17.4 33.8 31.7 28.2 27.4 24.5 12.7 17.9 14.4 14.1 16.6 20.9 23.5
 11.2 26.8 17.3 18.5 18.  27.  27.6 13.  27.2 27.5 26.4 15.8 28.3 25.7
 29.7 18.1 21.4 25.8 25.5 12.5 22.8 26.1 20.5 13.8 29.6 15.4 30.  14.
 13.2 25.3 23.2 17.1 27.1 23.6 34.7 22.6 26.9 19.9 19.1 19.  23.7 11.4
 18.4 30.7 23.8 23.  12.3 15.9 26.2 13.6 19.6 17.5 24.8 17.2 12.6 30.6
 31.1 22.2 17.6 31.9 17.  11.7 21.8 32.9 27.8 11.9 21.3 30.2 28.5 15.5
 28.6 34.3 11.6 24.9 11.3 33.1 26.5 16.2 26.  12.  24.1 27.7 29.  31.6
 29.3 29.1 23.3 13.1 14.5 29.9 30.5 32.  12.1 32.2 29.8 10.5 33.2 28.1
 25.1 30.1 10.4 28.4 28.9 24.4 10.9 33.6 31.8 29.4 10.7 29.2 10.6 25.6
 14.2 31.5 31.2 24.7 10.8 28.8 34.4 34.8 27.3 30.8 24.3 32.7 30.9 32.8]
----------------------------------------
----------------------------------------
stadtteil
['Königswiesen' 'Burgweinting' 'Galgenberg' 'Stadtamhof' 'Karthaus-Prüll'
 'Dechbetten' 'Reinhausen' 'Kasernenviertel' 'Westenviertel' 'Innenstadt'
 'Kumpfmühl' 'Ziegetsdorf' 'Großprüfening' 'Ostenviertel']
----------------------------------------
----------------------------------------
living_area_text
['21.2 m2' '18.8 m2' '16.3 m2' '20,4 qm' '22 m²' '20.6 m2' '18 m²'
 '21,7 qm' '15 m²' '16,7 qm' '17,8 qm' '21 m²' '13.5 m2' '22,1 qm'
 '15,6 qm' '34,0 qm' '23 m²' '22,7 qm' '26.6 m2' '24,6 qm' '19.3 m2'
 '13,9 qm' '28,0 qm' '22,9 qm' '12,4 qm' '20.1 m2' '11.8 m2' '22,4 qm'
 '26.3 m2' '22.0 m2' '12.2 m2' '11,5 qm' '23,1 qm' '20,0 qm' '19,8 qm'
 '18,3 qm' '14,7 qm' '24.6 m2' '20 m²' '19 m²' '22,3 qm' '13 m²' '14,9 qm'
 '23,4 qm' '24,2 qm' '20.3 m2' '17,7 qm' '15,3 qm' '30 m²' '20.4 m2'
 '19.2 m2' '26,7 qm' '25 m²' '21,1 qm' '16 m²' '16.4 m2' '27.9 m2'
 '31.0 m2' '21.7 m2' '14 m²' '19,3 qm' '15.6 m2' '16,0 qm' '18,2 qm'
 '18,6 qm' '21.5 m2' '12.8 m2' '21,6 qm' '16.8 m2' '19.5 m2' '16.5 m2'
 '16.0 m2' '16.9 m2' '23.9 m2' '14,6 qm' '14.3 m2' '15.7 m2' '20.0 m2'
 '28.0 m2' '31,3 qm' '11 m²' '25.4 m2' '20,7 qm' '19,4 qm' '25,9 qm'
 '17.4 m2' '28 m²' '34 m²' '19,7 qm' '25,4 qm' '32 m²' '14.7 m2' '27,4 qm'
 '24 m²' '12,7 qm' '31,0 qm' '12.4 m2' '13.9 m2' '14,4 qm' '14.1 m2'
 '16.6 m2' '18.9 m2' '15,0 qm' '14.8 m2' '18.7 m2' '11.2 m2' '27 m²'
 '16,6 qm' '17,3 qm' '16,3 qm' '27,6 qm' '13.0 m2' '16,5 qm' '27.2 m2'
 '26,4 qm' '15,8 qm' '28.3 m2' '25.7 m2' '29.7 m2' '18,1 qm' '21,4 qm'
 '15.1 m2' '26 m²' '17,4 qm' '25,5 qm' '20,3 qm' '22.9 m2' '12,5 qm'
 '16.7 m2' '16,1 qm' '21,2 qm' '19.7 m2' '26.7 m2' '26,8 qm' '13.8 m2'
 '29,6 qm' '15,4 qm' '30,0 qm' '14,0 qm' '13.2 m2' '25.3 m2' '25,2 qm'
 '23.2 m2' '16,4 qm' '17 m²' '33.8 m2' '14,3 qm' '25.2 m2' '17,1 qm'
 '23.6 m2' '34,7 qm' '24.5 m2' '18,5 qm' '22,6 qm' '18.3 m2' '15.8 m2'
 '20,1 qm' '19,9 qm' '19,1 qm' '22,0 qm' '19,0 qm' '23,7 qm' '20.9 m2'
 '27.6 m2' '11,4 qm' '31 m²' '18,7 qm' '12 m²' '16,9 qm' '23,8 qm'
 '19.8 m2' '23.0 m2' '23.4 m2' '20.2 m2' '20.5 m2' '29,7 qm' '27.1 m2'
 '13.6 m2' '20,6 qm' '19.1 m2' '17.1 m2' '18.5 m2' '22.4 m2' '26.4 m2'
 '12,3 qm' '13,5 qm' '22.5 m2' '25,3 qm' '31.1 m2' '17.6 m2' '15.2 m2'
 '17.0 m2' '17,0 qm' '17,9 qm' '16.1 m2' '20,8 qm' '11,7 qm' '21,8 qm'
 '32,9 qm' '26,1 qm' '11.9 m2' '21.1 m2' '19.9 m2' '23.5 m2' '18.4 m2'
 '12,9 qm' '17,2 qm' '30,2 qm' '24,5 qm' '15.9 m2' '23,6 qm' '22,5 qm'
 '30.7 m2' '21,9 qm' '18.6 m2' '35 m²' '27,1 qm' '17,5 qm' '28.6 m2'
 '20.8 m2' '34,3 qm' '21,5 qm' '17.2 m2' '30,6 qm' '15.5 m2' '14,1 qm'
 '23,5 qm' '15,2 qm' '23.1 m2' '26,6 qm' '14.6 m2' '21.3 m2' '18.0 m2'
 '33,1 qm' '21.9 m2' '25,7 qm' '23,9 qm' '23.7 m2' '26.5 m2' '30.2 m2'
 '24,8 qm' '26,9 qm' '16,2 qm' '26,0 qm' '13,7 qm' '18,8 qm' '27,0 qm'
 '19,2 qm' '20.7 m2' '28,6 qm' '21,3 qm' '21.0 m2' '23,0 qm' '20,2 qm'
 '27.7 m2' '29.0 m2' '31,6 qm' '13.4 m2' '29,3 qm' '11,0 qm' '27.4 m2'
 '29,1 qm' '22,8 qm' '15.3 m2' '16.2 m2' '23.3 m2' '13,3 qm' '25.5 m2'
 '13,1 qm' '27,2 qm' '26.0 m2' '21.6 m2' '15,7 qm' '17.3 m2' '30.4 m2'
 '31,1 qm' '18.2 m2' '17.8 m2' '15.4 m2' '19.6 m2' '23,3 qm' '27.0 m2'
 '23.8 m2' '29.9 m2' '31,7 qm' '19.0 m2' '32.0 m2' '18,0 qm' '32,2 qm'
 '14.0 m2' '29,8 qm' '10 m²' '25.9 m2' '28.5 m2' '16,8 qm' '33 m²'
 '28,1 qm' '13,6 qm' '13.7 m2' '24.8 m2' '29 m²' '30.1 m2' '19,5 qm'
 '18,9 qm' '28.4 m2' '11,2 qm' '21,0 qm' '24.4 m2' '28,2 qm' '14.5 m2'
 '22.3 m2' '33.6 m2' '22.1 m2' '31,8 qm' '26.9 m2' '28.9 m2' '26.1 m2'
 '24,9 qm' '29,4 qm' '21.8 m2' '17.9 m2' '27,5 qm' '10.6 m2' '22.2 m2'
 '26,5 qm' '19,6 qm' '33.2 m2' '22,2 qm' '17,6 qm' '26,3 qm' '20,5 qm'
 '14,5 qm' '26.2 m2' '17.5 m2' '12,2 qm' '28,3 qm' '13,4 qm' '29.4 m2'
 '19.4 m2' '22.7 m2' '24.9 m2' '31,2 qm' '21.4 m2' '25,8 qm' '23,2 qm'
 '25.6 m2' '25,6 qm' '24,4 qm' '14.4 m2' '24.2 m2' '15,5 qm' '28.1 m2'
 '28,5 qm' '18,4 qm' '10,6 qm' '27.8 m2' '26,2 qm' '12.1 m2' '24,7 qm'
 '13.3 m2' '11.4 m2' '25,0 qm' '10,8 qm' '15.0 m2' '20,9 qm' '13.1 m2'
 '15,9 qm' '25.1 m2' '34.7 m2' '18.1 m2' '29,9 qm' '33,6 qm' '34.4 m2'
 '32.2 m2' '34.8 m2' '28,9 qm' '27,9 qm' '30,8 qm' '13,8 qm' '14.2 m2'
 '22.8 m2' '25,1 qm' '24,3 qm' '12.6 m2' '29.3 m2' '24.1 m2' '32,7 qm'
 '28.2 m2' '10,9 qm' '27,3 qm' '13,0 qm' '29,0 qm' '11.7 m2' '32.8 m2']
----------------------------------------
----------------------------------------
energieausweis
['A+' 'E' 'D' 'A' 'B' 'G' 'F' 'C' 'H']
----------------------------------------
----------------------------------------
dist_uni_km
[ 7.5 10.8 10.7 10.9  9.4  1.8  3.4  4.3  6.2  8.6  3.7  1.7  2.4 10.1
 10.6  9.1  9.8  4.7  8.   9.5  4.6 11.1  5.   2.5  8.4  7.2 10.5  8.1
  4.9  4.5  9.3  6.   1.4  6.9 10.   9.9  9.6  1.1  7.   4.2  4.8  6.7
  7.7  7.4  2.2  8.7  1.2  7.6  6.3  4.4  2.7  1.5  6.1  8.9  2.9  5.7
  7.9  5.8  3.8  7.8  3.6  2.1  6.4  1.   6.8  4.1  5.2  6.6 11.   2.3
  5.6  3.1  9.  10.3  5.4  3.9  8.8  2.   3.2  0.9  5.1  6.5 11.4 10.4
 10.2 11.2  7.1  2.8  8.5  1.6  8.3  4.   5.5  9.2  5.9  9.7  8.2  3.3
  3.   7.3  5.3  2.6  3.5  1.9 11.5 11.3 11.6  1.3]
----------------------------------------
----------------------------------------
contact_type
['Genossenschaft' 'Makler' 'Privat']
----------------------------------------
----------------------------------------
heating_type
['Nachtspeicher' 'Gasetagenheizung' 'Fernwärme' 'Zentralheizung' 'Öl'
 'Pellet']
----------------------------------------
----------------------------------------
kitchen
['Pantry' 'Einbauküche' 'keine']
----------------------------------------
----------------------------------------
dist_uni_min
[30 44 43 37  7 14 17 24 35 15 11 41 42 39 19 32 38 18 20 10 33 29 36  6
 27 40  5 28 25  9 31 23 26 13  8 34 21 16 22 12 45]
----------------------------------------
----------------------------------------
elevator
['ja' 'nein']
----------------------------------------
----------------------------------------
clicks_last_week
[211  52  65 227  94 114 125 220 185 297 245  93  98 237 128 280  42 206
 138 122  31 110 155 181   9  24  89  18 130 275  22 202 299 123 251 140
 153 198 248 235 279  57 177 259 160 264 194 135 203 217 113 212  12  19
 149 208 191 169 180  56   8 103 239 229 141 107 116   7  21 230 265 242
 173 204 117 266 187 226 278 131 243  95  44  88 221 171  79  51   0 215
  36  14 247  15 287  48 193 241  77  69  87  62 158 109 263 276  30 285
 271 105  28 104 256 118 255  63   1  23 124 132 284 179 192 272  49  72
 182 197 186 207  59  50 195 152  16 216  41 273  96 165 129 142 161  82
  92 293  40 290  54 267 170  27   6 201 151 115 134  70 258 238 108 175
  66 159 277 143 167  73 190  43 292 183  85  34  53 300 168   3  33 218
 252 174 162  46 106 234  78 139 246 249  84 178 156 120  81 269  90 291
 127 200 281 262  86  29  55 172  39 257  17 240 210  76  26 133   4  91
  32  37 295 224  74 188 250 294  38  67 112 274 148 254 286 222 253 121
 119 145 213 189 126  61 289 228 244 166 231 214 288 147  60 137 136 163
 176 268 298  10  11 236  20   2 146 233 150 101  13 199 223  47  45 219
 164 209 205 102  68 225  99 260  83 270  35  80 196 184 296 261 232  97
  25   5 157 100 111 282 154  71 144  75  58  64]
----------------------------------------
----------------------------------------
listing_id
['INS-2026-49534' 'INS-2026-39524' 'INS-2026-45414' ... 'INS-2026-24228'
 'INS-2026-33925' 'INS-2026-38990']
----------------------------------------
----------------------------------------
nebenkosten_eur
[ 57 126 157 164 149  83  74  85 132 103  56 150  98 162 128 110  93 178
 108 112 102 123 100 134  73  58 153  76 125  63 163 117  50  70  68 116
 142  99  49 144  65  91  55  78  62  97 139 129 145 175 107  66 101  88
  81 113  87 148 187 118  77 141 119 161  72  84  92 111 127 138 199 124
 166  82 147  46 136  60 109 131  86  59 167 190 105 133 197  71 185  67
  94  95  90  89  54 135  75  80  61 140 120 159  79 152 151  64 181  96
 173 114 143  52 121 154 160  45 115 189 104 122  48 170 186 168 171 137
 203  53  69 155 146 106 169 182 179 174 156 180  40 158 165 176 194  47
  51 201 130 183  39 202 172]
----------------------------------------

Empty DataFrame
Columns: [kaltmiete_listing, overpriced, floor, furnished, num_photos, total_floors, building_age_years, listing_date, wg_typ, year_built, priority_score, num_rooms, plz, balcony, days_online, living_area_m2, stadtteil, living_area_text, energieausweis, dist_uni_km, contact_type, heating_type, kitchen, dist_uni_min, elevator, clicks_last_week, listing_id, nebenkosten_eur, is_dachgeschoss, floor_num]
Index: []

In [39]:
def drop_unleidige_columns(df: pd.DataFrame) -> pd.DataFrame:
    print("entferne unleidige Spalten")
    df=df.drop(["listing_id", "living_area_text","days_online","year_built","listing_date", "num_photos"], axis=1)
    return df

def mapping_floor_add_col_ist_dg(df: pd.DataFrame) -> pd.DataFrame:
    print("schreibe floor in ordinal um und füge spalte is_dachgeschoss hinzu")
    df["is_dachgeschoss"]= df["floor"] == "DG"

    
    df["floor_num"] = df["floor"].map({
                                        "Souterrain": -1,
                                        "EG": 0,
                                        "1. OG": 1,
                                        "2. OG": 2,
                                        "3. OG": 3,
                                        "4. OG": 4
                                    })
    #DG ist special
    df.loc[df["floor"] == "DG", "floor_num"] = df["total_floors"]
    df["floor_num"] = df["floor_num"].astype(int)
    return df

    
def clean_kaltmiete_listing(df: pd.DataFrame) -> pd.DataFrame:
    print("Bereinige Kaltmiete_listing")
    df['kaltmiete_listing'] = (
        df['kaltmiete_listing'].str.replace('€', '', regex=False)
                                .str.replace('EUR', '', regex=False)
                                .str.replace(',00', '', regex=False)
                                .str.replace('kalt', '', regex=False)
                                .str.replace('Kaltmiete:', '', regex=False)
                                .str.replace(' ', '', regex=False)
                                .str.strip()
                              )
    #nebenkosten rausrechnen
    df["ist_warm"] = df["kaltmiete_listing"].str.contains("warm", na=False) #nur zur kontrolle
    df["kaltmiete_vorher"] = df["kaltmiete_listing"] #nur zur kontrolle
    mask = df["kaltmiete_listing"].str.contains("warm", na=False)
    df.loc[mask, "kaltmiete_listing"] = (
    df.loc[mask, "kaltmiete_listing"]
      .str.replace("warm", "", regex=False)
      .astype(int)
      - df.loc[mask, "nebenkosten_eur"]
    )

    #in Zahl umwandeln
    df["kaltmiete_listing"]=(
    pd.to_numeric(df["kaltmiete_listing"], errors="coerce")
    .fillna(0)
    .astype(int)
    )    
    return df

In [45]:
def qm_preis_berechnen(df: pd.DataFrame) -> pd.DataFrame:
    print("Berechnet qm Preise")
    df["kaltmiete_qm"] = df["kaltmiete_listing"] / df["living_area_m2"]
    return df
def drop_absurde_qm_preise(df:pd.DataFrame, min=0, max=100) -> pd.DataFrame:
    print(f"Entferne preis/qm outlier, mindestpreis= {min}, höchstpreis={max}")
    print(f"{len(df)} Einträge im df")
    print(f"droppe {len(df[df["kaltmiete_qm"] <= min])} Einträge weil qm preis <={min}")
    print(f"droppe {len(df[df["kaltmiete_qm"] >= max])} Einträge weil qm preis >={max}")
    df = df[df["kaltmiete_qm"] >= min]
    df = df[df["kaltmiete_qm"] <= max]
    print(f"{len(df)} Einträge im df")
    return df

def mapping(df:pd.DataFrame) -> pd.DataFrame:
    print("mappe balcony, energieausweis,elevator")
    df["balcony"] = df["balcony"].map({"ja": True, "nein": False})
    df["energieausweis"] = df["energieausweis"].map({"A+": 8,
                                                    "A": 7,
                                                    "B": 6,
                                                    "C": 5,
                                                    "D": 4,
                                                    "E": 3,
                                                    "F": 2,
                                                    "G": 1,
                                                    "H": 0})
    df["elevator"] = df["elevator"].map({"ja": True, "nein": False})
    return df
def plz_als_str(df:pd.DataFrame) -> pd.DataFrame:
    print("plz als string")
    df["plz"] = df["plz"].astype(str) #PLZ sind keine echten Zahlen, sondern IDs für Regionen.als Kategorie encoden
    return df

def drop_helfer_spalten(df:pd.DataFrame):
    print("droppe helferspalten")
    df = df.drop(["kaltmiete_vorher", "ist_warm", "kaltmiete_qm"], axis=1)
    return df

In [50]:
def clean_me(df:pd.DataFrame) -> pd.DataFrame:
    df = drop_unleidige_columns(df)
    df = mapping_floor_add_col_ist_dg(df)
    df = clean_kaltmiete_listing(df)
    df = qm_preis_berechnen(df)
    df = drop_absurde_qm_preise(df,8,35)
    df = mapping(df)
    df = plz_als_str(df)
    df = drop_helfer_spalten(df)
    return df

In [51]:
cu_1 = train_original.copy()
cu_1 = drop_unleidige_columns(cu_1)
cu_1 = mapping_floor_add_col_ist_dg(cu_1)
cu_1 = clean_kaltmiete_listing(cu_1)
cu_1 = qm_preis_berechnen(cu_1)
cu_1 = drop_absurde_qm_preise(cu_1,8,35)
cu_1 = mapping(cu_1)
cu_1 = plz_als_str(cu_1)
cu_1 = drop_helfer_spalten(cu_1)

entferne unleidige Spalten
schreibe floor in ordinal um und füge spalte is_dachgeschoss hinzu
Bereinige Kaltmiete_listing
Berechnet qm Preise
Entferne preis/qm outlier, mindestpreis= 8, höchstpreis=35
1500 Einträge im df
droppe 15 Einträge weil qm preis <=8
droppe 2 Einträge weil qm preis >=35
1483 Einträge im df
mappe balcony, energieausweis,elevator
plz als string
droppe helferspalten

In [52]:

pd.set_option('display.max_rows', None)
display(cu_1)
pd.reset_option('display.max_rows')

      kaltmiete_listing  overpriced       floor     furnished  total_floors  \
0                   325       False       2. OG  teilmöbliert             2
1                   335        True       3. OG      möbliert             2
2                   334       False          EG    unmöbliert             2
3                   373       False       2. OG    unmöbliert             2
4                   328       False          EG  teilmöbliert             4
5                   301        True  Souterrain  teilmöbliert             1
6                   339        True          DG    unmöbliert             2
7                   382       False          DG    unmöbliert             2
8                   213       False          DG    unmöbliert             2
9                   306       False       2. OG    unmöbliert             4
10                  248       False       4. OG    unmöbliert             3
11                  414        True       4. OG    unmöbliert             7
12                  320        True          EG  teilmöbliert             1
13                  317        True       1. OG      möbliert             6
14                  648        True       1. OG      möbliert             7
15                  316        True       4. OG      möbliert             4
16                  210       False       1. OG    unmöbliert             3
17                  604       False       1. OG    unmöbliert             4
18                  309       False       1. OG  teilmöbliert             1
19                  246       False          EG    unmöbliert             3
20                  334       False       3. OG    unmöbliert             3
21                  567       False       1. OG    unmöbliert             4
22                  262       False       2. OG    unmöbliert             5
23                  262       False       2. OG    unmöbliert             6
24                  463        True  Souterrain      möbliert             4
25                  336       False          EG  teilmöbliert             4
26                  432       False       2. OG    unmöbliert             4
27                  220       False  Souterrain    unmöbliert             6
28                  454        True       4. OG      möbliert             5
29                  162       False          EG  teilmöbliert             1
30                  453        True       2. OG    unmöbliert             5
31                  357       False          EG    unmöbliert             1
32                  341        True          EG  teilmöbliert             3
33                  238       False       3. OG    unmöbliert             2
34                  314        True       2. OG  teilmöbliert             5
35                  425       False       4. OG    unmöbliert             2
36                  219       False          DG  teilmöbliert             2
37                  223        True       2. OG    unmöbliert             5
38                  359        True          EG  teilmöbliert             7
39                  214       False          DG    unmöbliert             7
40                  433       False          DG      möbliert             1
41                  292       False          DG    unmöbliert             3
42                  331        True          EG      möbliert             3
43                  237       False       3. OG    unmöbliert             5
44                  305       False          EG    unmöbliert             5
45                  503        True       2. OG  teilmöbliert             4
46                  271       False  Souterrain      möbliert             1
47                  400       False          EG  teilmöbliert             4
48                  239       False  Souterrain    unmöbliert             4
49                  342        True          EG      möbliert             7
50                  459        True       2. OG      möbliert             3
51                  142       False          DG  teilmöbliert             4
52                  222       False       2. OG    unmöbliert             1
54                  462        True       3. OG      möbliert             1
55                  348       False       3. OG    unmöbliert             4
56                  518        True          EG    unmöbliert             5
57                  334       False       1. OG      möbliert             7
58                  331       False       2. OG    unmöbliert             6
59                  133       False       3. OG    unmöbliert             1
60                  592       False       1. OG    unmöbliert             6
61                  318       False       1. OG  teilmöbliert             2
62                  460        True       2. OG      möbliert             2
63                  439        True          DG  teilmöbliert             6
64                  349        True       2. OG    unmöbliert             6
65                  352       False       2. OG    unmöbliert             5
66                  427        True       2. OG  teilmöbliert             3
67                  340        True       2. OG  teilmöbliert             4
68                  447        True       1. OG    unmöbliert             4
69                  297        True          EG      möbliert             6
70                  367       False  Souterrain    unmöbliert             3
71                  419        True       1. OG      möbliert             3
72                  865        True       2. OG      möbliert             7
73                  378        True       1. OG    unmöbliert             3
74                  581        True       1. OG    unmöbliert             2
75                  259        True       2. OG      möbliert             6
76                  349        True       1. OG    unmöbliert             5
77                  422        True       2. OG      möbliert             6
78                  195       False       1. OG  teilmöbliert             1
79                  343       False       3. OG    unmöbliert             4
80                  397        True       2. OG    unmöbliert             7
81                  280        True       1. OG      möbliert             3
82                  315       False       2. OG    unmöbliert             6
83                  287       False          DG    unmöbliert             1
84                  500       False          EG    unmöbliert             3
85                  327       False       2. OG  teilmöbliert             7
86                  329        True       4. OG      möbliert             6
87                  290        True       1. OG    unmöbliert             4
88                  298        True       2. OG  teilmöbliert             5
89                  451        True          EG      möbliert             3
90                  480        True       1. OG    unmöbliert             6
91                  330        True          EG  teilmöbliert             5
92                  309       False          EG    unmöbliert             1
93                  358        True          EG      möbliert             2
94                  230       False       2. OG    unmöbliert             1
95                  265       False       2. OG    unmöbliert             2
96                  332       False       1. OG    unmöbliert             7
97                  431       False          EG    unmöbliert             3
98                  373        True       3. OG    unmöbliert             7
99                  232        True       2. OG  teilmöbliert             5
100                 251        True       3. OG    unmöbliert             2
101                 267        True       2. OG    unmöbliert             2
102                 301       False          EG      möbliert             2
103                 576        True  Souterrain    unmöbliert             5
104                 275        True       1. OG  teilmöbliert             2
105                 485       False       2. OG      möbliert             1
106                 213       False       1. OG    unmöbliert             1
107                 365       False          EG    unmöbliert             7
108                 377        True          DG    unmöbliert             1
109                 534        True       1. OG    unmöbliert             3
110                 315       False       1. OG  teilmöbliert             5
111                 295       False          DG    unmöbliert             4
112                 520        True          EG    unmöbliert             3
113                 411        True       3. OG      möbliert             2
114                 327       False       3. OG    unmöbliert             5
115                 619        True       1. OG    unmöbliert             5
116                 362       False       2. OG    unmöbliert             7
117                 894        True          EG  teilmöbliert             3
118                 333        True       1. OG  teilmöbliert             5
119                 384       False       2. OG  teilmöbliert             6
120                 430       False       1. OG    unmöbliert             1
121                 398        True       4. OG  teilmöbliert             7
122                 297        True       3. OG    unmöbliert             2
123                 608       False       1. OG  teilmöbliert             2
124                 181       False       3. OG  teilmöbliert             5
125                 666        True          EG  teilmöbliert             5
126                 352       False       2. OG    unmöbliert             6
127                 235        True          DG      möbliert             5
128                 369       False          DG    unmöbliert             6
129                 454       False       3. OG    unmöbliert             2
130                 151       False          DG  teilmöbliert             3
131                 200       False       3. OG    unmöbliert             7
132                 477        True       3. OG  teilmöbliert             5
133                 330        True       1. OG    unmöbliert             6
134                 245       False          DG    unmöbliert             4
135                 222       False       1. OG    unmöbliert             7
136                 184       False          DG    unmöbliert             6
137                 228        True          EG  teilmöbliert             5
138                 324        True       2. OG      möbliert             7
139                 246       False       2. OG  teilmöbliert             4
140                 429        True          DG  teilmöbliert             2
141                 241        True       1. OG  teilmöbliert             1
142                 406        True          DG    unmöbliert             3
143                 279       False       2. OG  teilmöbliert             2
144                 371        True       4. OG    unmöbliert             4
145                 457       False          DG  teilmöbliert             7
146                 420       False          DG    unmöbliert             1
147                 227        True       3. OG    unmöbliert             2
148                 370       False       3. OG  teilmöbliert             7
149                 287       False          EG      möbliert             6
150                 634        True       2. OG      möbliert             7
151                 368        True       3. OG  teilmöbliert             6
152                 230       False  Souterrain    unmöbliert             4
153                 249       False          EG    unmöbliert             5
154                 209        True       2. OG    unmöbliert             1
155                 256       False       2. OG    unmöbliert             1
156                 338       False          EG  teilmöbliert             6
157                 276        True          EG  teilmöbliert             4
158                 304        True       2. OG      möbliert             6
159                 540        True       1. OG      möbliert             7
160                 613        True       3. OG  teilmöbliert             2
161                 175       False          DG    unmöbliert             6
162                 264       False       2. OG    unmöbliert             1
163                 224       False          EG  teilmöbliert             7
164                 412       False       2. OG    unmöbliert             7
165                 344       False          EG    unmöbliert             4
166                 354       False          EG    unmöbliert             2
167                 259       False       4. OG      möbliert             2
168                 451       False          DG    unmöbliert             7
169                 577       False       1. OG    unmöbliert             2
170                 412       False       1. OG    unmöbliert             4
171                 643        True       2. OG  teilmöbliert             5
172                 236       False       2. OG    unmöbliert             2
173                 276       False  Souterrain    unmöbliert             2
174                 368        True          EG    unmöbliert             1
175                 264       False       3. OG      möbliert             7
176                 364       False       3. OG    unmöbliert             5
177                 271        True          DG    unmöbliert             5
178                 383        True       1. OG  teilmöbliert             2
179                 364       False       3. OG    unmöbliert             2
180                 300        True  Souterrain      möbliert             5
181                 286       False       1. OG    unmöbliert             1
182                 315       False       2. OG    unmöbliert             4
183                 239       False       4. OG    unmöbliert             7
184                 217        True       4. OG    unmöbliert             7
186                 357       False  Souterrain    unmöbliert             3
187                 301        True       3. OG  teilmöbliert             4
188                 290        True       4. OG    unmöbliert             4
189                 865        True          EG  teilmöbliert             1
190                 347        True       4. OG  teilmöbliert             3
191                 264       False  Souterrain    unmöbliert             2
192                 232       False       4. OG    unmöbliert             7
193                 344       False          DG  teilmöbliert             5
194                 705        True       2. OG  teilmöbliert             6
195                 223       False       4. OG  teilmöbliert             4
196                 510        True       2. OG  teilmöbliert             6
197                 173       False       4. OG      möbliert             4
198                 361        True       4. OG    unmöbliert             5
199                 169       False          DG    unmöbliert             1
200                 328       False          EG    unmöbliert             4
201                 271       False          EG    unmöbliert             7
202                 617        True  Souterrain  teilmöbliert             1
203                 224       False       3. OG    unmöbliert             1
204                 172       False          EG  teilmöbliert             6
205                 361        True       1. OG  teilmöbliert             2
206                 353       False       2. OG  teilmöbliert             7
207                 402        True       1. OG      möbliert             7
208                 373       False          EG    unmöbliert             7
209                 311       False          EG    unmöbliert             4
210                 792        True       3. OG      möbliert             3
211                 275        True       1. OG  teilmöbliert             4
212                 249       False       1. OG    unmöbliert             5
213                 414        True       1. OG    unmöbliert             5
214                 440       False          DG    unmöbliert             6
215                 184       False       3. OG  teilmöbliert             7
216                 294        True       1. OG  teilmöbliert             7
217                 470       False       4. OG    unmöbliert             6
218                 210        True       1. OG    unmöbliert             2
219                 435        True          EG    unmöbliert             3
220                 582        True       3. OG    unmöbliert             7
221                 232       False       2. OG  teilmöbliert             5
222                 408        True  Souterrain  teilmöbliert             7
223                 485        True       2. OG      möbliert             2
224                 383       False       3. OG  teilmöbliert             2
225                 459        True          DG    unmöbliert             3
226                 257        True       4. OG  teilmöbliert             4
227                 506        True          EG    unmöbliert             6
228                 315        True          EG    unmöbliert             3
229                 435       False          EG      möbliert             5
230                 476        True       1. OG  teilmöbliert             3
231                 389       False  Souterrain  teilmöbliert             1
232                 285        True          DG    unmöbliert             2
233                 266       False       3. OG    unmöbliert             7
234                 228       False          DG    unmöbliert             7
235                 479        True       3. OG  teilmöbliert             4
236                 562        True       2. OG  teilmöbliert             5
237                 391       False       3. OG      möbliert             3
238                 392        True          EG  teilmöbliert             3
239                 571       False       4. OG    unmöbliert             2
240                 200       False       2. OG  teilmöbliert             4
241                 324       False       3. OG    unmöbliert             3
242                 406       False          EG    unmöbliert             3
243                 285       False          EG    unmöbliert             2
244                 214       False          EG    unmöbliert             6
245                 476        True       3. OG      möbliert             1
246                 512        True          DG      möbliert             4
247                 558        True       4. OG      möbliert             2
248                 525        True       2. OG    unmöbliert             2
249                 259       False       3. OG    unmöbliert             2
250                 230       False          DG    unmöbliert             5
251                 502       False       1. OG    unmöbliert             5
252                 236       False          EG    unmöbliert             6
253                 268       False          DG    unmöbliert             7
254                 408       False          DG  teilmöbliert             5
255                 568        True       2. OG    unmöbliert             3
256                 157       False          EG    unmöbliert             1
257                 514        True       1. OG    unmöbliert             1
258                 320       False       2. OG    unmöbliert             1
259                 210       False       2. OG    unmöbliert             1
260                 319       False       1. OG    unmöbliert             1
261                 462        True       2. OG  teilmöbliert             3
262                 306        True       2. OG    unmöbliert             6
263                 400       False       2. OG    unmöbliert             5

## ML

In [49]:
train =train_original.copy()
train = clean_me(train)

train.head()

entferne unleidige Spalten
schreibe floor in ordinal um und füge spalte is_dachgeschoss hinzu
Bereinige Kaltmiete_listing
Berechnet qm Preise
Entferne preis/qm outlier, mindestpreis= 8, höchstpreis=35
1500 Einträge im df
droppe 15 Einträge weil qm preis <=8
droppe 2 Einträge weil qm preis >=35
1483 Einträge im df
mappe balcony, energieausweis,elevator
plz als string
droppe helferspalten

,kaltmiete_listing,overpriced,floor,furnished,total_floors,building_age_years,wg_typ,priority_score,num_rooms,plz,balcony,living_area_m2,stadtteil,energieausweis,dist_uni_km,contact_type,heating_type,kitchen,dist_uni_min,elevator,clicks_last_week,nebenkosten_eur,is_dachgeschoss,floor_num
0,325,False,2. OG,teilmöbliert,2,126,gemischt,7,3.0,93051,False,21.2,Königswiesen,8,7.5,Genossenschaft,Nachtspeicher,Pantry,30,True,211,57,False,2
1,335,True,3. OG,möbliert,2,105,gemischt,9,2.0,93055,True,18.8,Burgweinting,8,10.8,Makler,Gasetagenheizung,Einbauküche,44,False,52,126,False,3
2,334,False,EG,unmöbliert,2,50,Studenten-WG,5,1.0,93053,True,16.3,Galgenberg,3,10.7,Privat,Gasetagenheizung,Einbauküche,43,False,65,157,False,0
3,373,False,2. OG,unmöbliert,2,18,Studenten-WG,6,3.0,93059,False,20.4,Stadtamhof,3,10.9,Privat,Fernwärme,Einbauküche,44,False,227,164,False,2
4,328,False,EG,teilmöbliert,4,35,Studenten-WG,7,3.0,93049,False,22.5,Karthaus-Prüll,4,9.4,Privat,Zentralheizung,Einbauküche,37,False,94,149,False,0

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

#classifiers
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier

#regressors